Upgrade to openssh-portable to 9.3p1 and Alpine Linux 3.18
To support Alpine Linux 3.18 and other Linux distributions with new
versions of LibreSSL/OpenSSL, upgrade openssh-portable from 7.3p1 to
9.3p1.

As a welcome side effect of the upgrade, the realpath compatibility
patch is not needed anymore.

Changes in the LibreSSL/OpenSSL API resulted in the following compile
error that is addressed by this upgrade:
```
gcc -g -O2 -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wsizeof-pointer-memaccess -Wno-pointer-sign -Wno-unused-result -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -ftrapv -fno-builtin-memset -fstack-protector-strong -fPIE  -I. -I.  -DSSHDIR=\"/usr/local/etc\" -D_PATH_SSH_PROGRAM=\"/usr/local/bin/ssh\" -D_PATH_SSH_ASKPASS_DEFAULT=\"/usr/local/libexec/ssh-askpass\" -D_PATH_SFTP_SERVER=\"/usr/local/libexec/sftp-server\" -D_PATH_SSH_KEY_SIGN=\"/usr/local/libexec/ssh-keysign\" -D_PATH_SSH_PKCS11_HELPER=\"/usr/local/libexec/ssh-pkcs11-helper\" -D_PATH_SSH_PIDDIR=\"/var/run\" -D_PATH_PRIVSEP_CHROOT_DIR=\"/var/empty\" -DHAVE_CONFIG_H -c ssh_api.c -o ssh_api.o
In file included from ssh_api.h:26,
                 from ssh_api.c:20:
cipher.h:69:24: error: field 'evp' has incomplete type
   69 |         EVP_CIPHER_CTX evp;
      |                        ^~~
make: *** [Makefile:152: ssh_api.o] Error 1
```